name: questionnaires
description: A flutter questionnaire app.
version: 1.0.0+1
author: Julian Schwab

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dots_indicator: ^2.1.0
  expressions: ^0.2.4
  checkbox_grouped: ^1.8.1
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.6
  auto_size_text: ^3.0.0
  sqflite: ^2.2.0+3
  path: ^1.8.2
  path_provider: ^2.0.11 
  http: ^0.13.5
  easy_actions: ^1.1.0
  shared_preferences: ^2.0.15
  webviewx: ^0.2.1
  group_button: ^5.2.2
  flutter_group_button: ^1.0.1
  responsive_grid_list:
  provider: ^6.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/questionnaires/
   - assets/infos/
   - assets/images/
   - assets/images/ce-zei.png
   - assets/icons/
   - assets/about/

fonts:
  - family: Raleway
    fonts: 
      - asset: fonts/Raleway-Regular.ttf
      - asset: fonts/Raleway-Italic.ttf
        style: italic
flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets_dev/app_icon.png"

  analyzer:
  enable-experiment:
  - non-nullable